# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chivia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chivia
  pod 'Alamofire', '~> 4.5'
  pod 'LGButton'
  pod 'Mapbox-iOS-SDK', '~> 3.6'
  pod 'MapboxNavigation', '~> 0.9'
  pod 'MZFormSheetPresentationController'
  pod 'PromiseKit', '~> 4.4'
  pod 'SwiftyJSON'
  pod 'Toast-Swift', '~> 2.0.0'
  
  post_install do |installer|

      # https://github.com/CocoaPods/CocoaPods/issues/5334#issuecomment-255831772
      installer.pods_project.build_configurations.each do |config|
          config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
              '$(FRAMEWORK_SEARCH_PATHS)'
          ]
      end
      
      # Set Pods Swift version to 3.2
      installer.pods_project.targets.each do |target|
          if not ['LGButton'].include?(target.name)
              target.build_configurations.each do |config|
                  config.build_settings['SWIFT_VERSION'] = '3.2'
              end
          end
      end
  end

end
