# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chivia' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Chivia
  pod 'Alamofire', '~> 4.5'
  pod 'MapboxNavigation', '~> 0.9'

end
